criando api library
iytzpronet/BreakevenStone pull request #1
Opened 2023-04-05 12:37 UTC by iytzpronet

swagger da aplicaçao 
![enter image description here](https://github.com/iytzpronet/BreakevenStone/blob/main/swagger%20libraryapi.jpg?raw=tru)

2023-04-27 17:18 UTC, Luuck4s commented on LibraryApi/Controller/Contracts/CreateBookRequest.cs
> +    public string title { get; set; }
Aqui seria interessante os nomes seguirem o padrão de iniciar o com a letra maiúscula.
Exemplo: Title, PublishDate, TotalPages
Referência: https://learn.microsoft.com/pt-br/dotnet/csharp/fundamentals/coding-style/coding-conventions

2023-04-27 17:18 UTC, Luuck4s commented on LibraryApi/Config/Program.cs
> +builder.Services.AddTransient<IUserRepository, UserRepository>();
Está faltando o registro dos outros repositórios também:
```csharp
builder.Services.AddTransient<IBookRepository, BookRepository>();
```

2023-05-25 23:08 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/1deb42e6-31e9-4b26-b544-00233933b015)

2023-05-25 23:22 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/5c28608e-c7eb-4144-8a9e-4d458df24a82)
listando usuário

2023-05-25 23:37 UTC, iytzpronet commented
![put atualizar usuario](https://github.com/iytzpronet/BreakevenStone/assets/121514301/0b0f795b-0189-499c-9e3b-57e6643129df)
atualizando usuario

2023-05-25 23:41 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/1cb5e6ce-ea10-4854-92cd-868753e2ed72)
deletando usuario

2023-05-26 00:08 UTC, iytzpronet commented
![criando book](https://github.com/iytzpronet/BreakevenStone/assets/121514301/500422c0-2d10-457a-9532-77cb4a8a30e1)
criando book testando regra de negocio

2023-05-26 00:13 UTC, iytzpronet commented
![buscando livro get](https://github.com/iytzpronet/BreakevenStone/assets/121514301/535593a2-82ae-4319-83be-843942c3a603)
buscando lista de usuario getall

2023-05-26 00:15 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/6af2722b-102c-4519-9129-474d7334d2f1)
buscando livros por ID

2023-05-26 00:17 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/8dc4fe9c-afca-4f09-95dc-320398b8be5a)
atualizando usuario por ID

2023-05-26 00:21 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/d53f4606-4213-427e-b876-38158f2be5f6)
criando transação

2023-05-26 00:23 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/c56e82e2-7656-410f-91c5-dfebe7551dec)
listando transação

2023-05-26 00:26 UTC, iytzpronet commented
![image](https://github.com/iytzpronet/BreakevenStone/assets/121514301/8106a4e9-da6e-44cf-92db-cf68b348aedb)
tentando deletar um livro com um transação ativa

2023-05-30 16:32 UTC, riqueferr requested changes

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Controller/BookController.cs
> +    [HttpPut("Update/{id}")]
meu bom, acho que poderia padronizar tirando da URI o "update", por exemplo:
ao invés de `[HttpPut("Update/{id}")]` ser `[HttpPut("{id}")]`.

se fizer sentido para você, replica para os demais.
dá uma olhadinha neste artigo (tá em port e fácil entendimento): https://www.brunobrito.net.br/api-restful-boas-praticas/

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Controller/Contracts/CreateUserRequest.cs
> +    public bool validate ()
sugestão de melhoria para este método:
```
public bool Validate()
{
    return Name.Length >= 3;
}
```

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Controller/Validators/CreateBookValidator.cs
> +            RuleFor(x => x.Title).NotEmpty().MinimumLength(3).WithMessage("O título deve ter pelo menos 3 caracteres.").MaximumLength(10).WithMessage("O título deve ter no maximo 10 caracteres.");
acha válido deixar uma variável constante para substituir onde é passado valores mockados? facilitaria uma futura manutenção caso seja necessário! exemplo:

Ao invês de passar `.MaximumLength(10)` criar uma variavel `maximumLength = 10` e passaria ela no parâmetro `.MaximumLength(maximumLength)`

se fizer sentido, aplica para os demais e nas outras validações de request

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Entity/WeatherForecast.cs
> +public class WeatherForecast
este carinha está sendo usado? caso não, acho que pode apagar

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Repository/BookRepository.cs
> +       return await _context.Transaction.Where(b => b.BookId  == book.Id && b.Type==TransactionType.CHECKOUT).ToListAsync();
dá um espacinho no `==` entre `b.Type` e `TransactionType.CHECKOUT`

2023-05-30 16:32 UTC, riqueferr commented on LibraryApi/Repository/BookRepository.cs
> +        return await _context.Book.FirstOrDefaultAsync(x=>x.Id == id);
dá um espacinho no `=>` entre `x` e `x.Id`

2023-05-30 19:06 UTC, thaifurforo commented on LibraryApi/Entity/Transaction.cs
> +public enum TransactionType
O Enum é tipo uma classe, seria boa prática colocar ele em um arquivo separado
Sugestão colocar uma pasta Enumerations e dentro dela colocar todos os Enums do projeto

2023-05-30 19:06 UTC, thaifurforo commented on LibraryApi/Repository/BookRepository.cs
> +       return await _context.Transaction.Where(b => b.BookId  == book.Id && b.Type==TransactionType.CHECKOUT).ToListAsync();
Em `b.BookId  ==`
Tá com dois espaços entre o `b.BookId` e o `==`
Sugestão apagar um, deixar só um espaço

2023-05-30 19:07 UTC, thaifurforo commented
Muito bem evidenciado o PR, parabéns

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Context/LibraryContext.cs
> +}
```suggestion
public class LibraryContext:DbContext
{
    public DbSet<User> User { get; set; }
    public DbSet<Book> Book { get; set; }
    public DbSet<Transaction> Transaction { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new BookMapping());
        modelBuilder.ApplyConfiguration(new UserMapping());
        modelBuilder.ApplyConfiguration(new TransactionMapping());
    }

    public LibraryContext(DbContextOptions<LibraryContext> dbContextOptions): base(dbContextOptions)
    { }
}
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Config/Program.cs
> +
Achei a leitura desse arquivo meio confusa, sugiro dar uma melhorada (padronizada) nas quebras de linha

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/BookController.cs
> +    {
Sempre quebrar linha entre o construtor e o método para manter o código organizado e fácil de ler

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/BookController.cs
> +    }
quebrar linha

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/BookController.cs
> +        }
Não ficou muito claro para mim qual validação está sendo realizada abaixo, acredito que esse método Verify(), não deixa muito claro o que está sendo verificado e o UnprocessableEntity() não está especificando o motivo da falha.

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/Contracts/CreateTransactionRequest.cs
> +
```suggestion
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/Contracts/CreateUserRequest.cs
> +    public string Document { get; set; }
Por convenção de código e boas práticas, é importante primeiro declarar as propriedades e depois os métodos

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/TransactionController.cs
> +    public void Add(CreateTransactionRequest createTransactionRequest)
```suggestion
    }

    [HttpPost("Add")]
    public void Add(CreateTransactionRequest createTransactionRequest)
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/TransactionController.cs
> +    public async Task<List<Transaction>> List ()
```suggestion
    }

    [HttpGet("List")]
    public async Task<List<Transaction>> List ()
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/UserController.cs
> +    }
Ajustar a formatação do arquivo

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/UserController.cs
> +        [HttpDelete("Delete/{id}")]
Aqui é bom aplicar o comentário do @riqueferr também.

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/UserController.cs
> +            _repository.Delete(user);
Quebrar linha

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/Validators/CreateBookValidator.cs
> +            RuleFor(x => x.Title).NotEmpty().MinimumLength(3).WithMessage("O título deve ter pelo menos 3 caracteres.").MaximumLength(10).WithMessage("O título deve ter no maximo 10 caracteres.");
https://diegofranca.dev/2021/01/26/clean-code-numeros-magicos/

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/Validators/CreateTransactionValidator.cs
> +{
Na versão do .net que vc está utilizando, não é necessário declarar `{ }` para o namespace

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Controller/Validators/CreateUserValidator.cs
> +
apagar linha em branco

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Entity/Book.cs
> +    public Book()
quebrar linha

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Entity/Transaction.cs
> +public enum TransactionType
Mover esse enum para uma classe separada

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Entity/Transaction.cs
> +    RETURN = 1 ,
```suggestion
    RETURN = 1
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Entity/WeatherForecast.cs
> +public class WeatherForecast
Aqui é arquivo inicial do template webAPI, pode ser removido

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Mapping/BookMapping.cs
> +
```suggestion
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Mapping/TransactionMapping.cs
> +
```suggestion
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Mapping/UserMapping.cs
> +
```suggestion
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/BookRepository.cs
> +    public void Add(Book book)
```suggestion
    }

    public void Add(Book book)
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/BookRepository.cs
> +public class BookRepository : IBookRepository
Ajustar a formatação desse arquivo, quebrar linhas entre os métodos

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/BookRepository.cs
> +
```suggestion
```

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/IBookRepository.cs
> +    public Task<List<Transaction>> Verify(Book book);
Não precisa declarar modificadores de acesso (public, private, protected) para as propriedades de uma interface

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/UserRepository.cs
> +public class UserRepository : IUserRepository
Ajustar quebra de linha entres os métodos desse arquivo

2023-05-30 19:19 UTC, causticsudo commented on LibraryApi/Repository/UserRepository.cs
> +    private readonly LibraryContext context;
Por conveção de código, propriedades de somente leitura (readonly) recebem um prefixo `_`
```suggestion
    private readonly LibraryContext _context;
```

2023-05-30 19:22 UTC, causticsudo commented
Parabéns pelas evidências, só senti falta de testes unitários !

2023-06-01 12:11 UTC, iytzpronet commented on LibraryApi/Repository/BookRepository.cs
> +       return await _context.Transaction.Where(b => b.BookId  == book.Id && b.Type==TransactionType.CHECKOUT).ToListAsync();
ok resolvido

2023-06-01 12:12 UTC, iytzpronet commented on LibraryApi/Repository/BookRepository.cs
> +        return await _context.Book.FirstOrDefaultAsync(x=>x.Id == id);
ok resolvido

2023-06-01 12:12 UTC, iytzpronet commented on LibraryApi/Repository/BookRepository.cs
> +       return await _context.Transaction.Where(b => b.BookId  == book.Id && b.Type==TransactionType.CHECKOUT).ToListAsync();
ok resolvido

2023-06-01 12:12 UTC, iytzpronet commented on LibraryApi/Controller/BookController.cs
> +    [HttpPut("Update/{id}")]
resolvido , eu tinha me esquecido de subir a ATT do codigo

2023-06-01 12:16 UTC, iytzpronet commented on LibraryApi/Controller/BookController.cs
> +    {
ok resolvido

2023-06-01 12:23 UTC, iytzpronet commented on LibraryApi/Controller/BookController.cs
> +        }
qual sugestao?

2023-06-01 12:24 UTC, iytzpronet commented on LibraryApi/Repository/BookRepository.cs
> +public class BookRepository : IBookRepository
resolvido

2023-06-01 12:26 UTC, iytzpronet commented on LibraryApi/Repository/BookRepository.cs
> +
resolvido

2023-06-01 12:35 UTC, iytzpronet commented on LibraryApi/Repository/UserRepository.cs
> +    private readonly LibraryContext context;
certo resolvido

2023-06-01 13:22 UTC, iytzpronet commented on LibraryApi/Repository/UserRepository.cs
> +public class UserRepository : IUserRepository
ok resolvido

2023-06-23 19:10 UTC, riqueferr requested changes

2023-06-23 19:10 UTC, riqueferr commented on LibraryApi/Controller/BookController.cs
> +    public async Task<Book> getbyid(Guid id)
Recomenda-se usar `PascalCase` para nomes de métodos: `GetById`

2023-06-23 19:10 UTC, riqueferr commented on LibraryApi/Controller/TransactionController.cs
> +    public async Task<List<Transaction>> List ()
Deixa o `()` junto com o nome do método, meu toque atacou rs.
Apenas como sugestão: este método é uma `List` do que? Ficou genérico, saca? Se ele trouxer tudo (sem passar parâmetros), sugiro `ListAll()` ou `GetAllTransactions()`

2023-06-23 19:10 UTC, riqueferr commented on LibraryApi/Controller/UserController.cs
> +        public async Task<List<User>> List ()
Existe um espaço entre o nome do método e o `()`

2023-06-23 19:16 UTC, riqueferr commented on LibraryApi/Controller/BookController.cs
> +        }
mathusao, dá uma olhada no método `Delete` do `BookController`. Nele, você fez praticamente o que o matheusin está sugerindo. Vê a diferença e replica

2023-06-23 19:19 UTC, riqueferr commented
Soltei mais alguns ajustes de `Boa Prática`! Parabéns, meu mano!

2023-06-29 13:14 UTC, causticsudo approved these changes

2023-06-29 13:20 UTC, Luuck4s commented on LibraryApi/Controller/BookController.cs
> +            return book;
Ajustar formatação

2023-06-29 13:26 UTC, thaifurforo approved these changes

2023-06-29 13:26 UTC, thaifurforo commented on LibraryApi/Entity/Transaction.cs
> +public enum TransactionStatus
esse Enum deve ir para um arquivo separado

2023-06-29 13:49 UTC, riqueferr approved these changes

2023-06-29 14:16 UTC, Luuck4s commented on LibraryApi/Controller/UserController.cs
> +            this._userRepository = userRepository;
Esse this. pode ser removido daqui

2023-06-29 14:16 UTC, Luuck4s commented on LibraryApi/Entity/WeatherForecast.cs
> +namespace LibraryApi;
Esse arquivo pode ser removido

2023-06-29 14:17 UTC, Luuck4s approved these changes

2023-06-29 15:12 UTC, merged